"use client"
import { FloatingNav } from '@/components/ui/floating-navbar'
import { navItems } from '@/data/index'
import { Metadata } from 'next'
import Head from 'next/head'
import React from 'react'

const metadata: Metadata = {
  title: "Dev-Bry",
  description: "Generated by create next app",
};

function HeadContent() {
  return (
    <Head>
      <title>{String(metadata.title) || "Default Title"}</title>
      <meta name="description" content={String(metadata.description) || "Default Description"} />
      <meta property="og:title" content={String(metadata.title) || "Default Title"} />
      <meta property="og:description" content={String(metadata.description) || "Default Description"} />
      <meta property="og:image" content="/default.png" key="og-image"  />
      <meta property="og:url" content="https://dev-bry.vercel.app" />
      <meta name="twitter:card" content="summary_large_image" />
    </Head>
  );
}

const HomeLayout = ({children}:{children:React.ReactNode}) => {
  return (
    <section className='h-screen bg-slate-50 dark:bg-slate-900'>
      <HeadContent/>
       <FloatingNav navItems={navItems} />
        {children}
    </section>
  )
}

export default HomeLayout
